### ISSUE TITLE
How to get the colorEcho?

### ISSUE THREAD

**Issue by liangzai-cool** [cdnjs/buildScript#38]
thank you!
come from https://github.com/cdnjs/new-website/issues/108
I am learning the code of this project, I already see line 29 of `buildScript/update-website.sh`(See https://github.com/cdnjs/buildScript/blob/master/update-website.sh#L29), I found no `$pth/colorEcho/dist/ColorEcho.bash` file. How to get the colorEcho which like a plugin? I use windows.
thank you!

**Comment by liangzai-cool** [comment]
thank you! I got it!
https://github.com/PeterDaveHello/ColorEchoForShell

**Comment by PeterDaveHello** [comment]
`git submodule update --init`

**Comment by liangzai-cool** [comment]
thank you!

**Comment by PeterDaveHello** [comment]
@liangzai-cool no probs
